[package]
name = "BlobUtils"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Studio Mirai, LLC (dev@sm.xyz)"]

[dependencies]
codec = { r.mvr = "@potatoes/codec" }

[addresses]
blob_utils = "0x0"

[r.mvr]
network = "testnet"
