[package]
name = "BlobUtils"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Studio Mirai, LLC (dev@sm.xyz)"]

[dependencies]
Codec = { git = "https://github.com/sui-potatoes/app.git", subdir = "packages/codec", rev = "main" }

[addresses]
blob_utils = "0x0"